- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: enable frp server
  ansible.builtin.systemd:
    name: frps
    enabled: yes

- name: start frp server
  ansible.builtin.systemd:
    name: frps
    state: started