---
- name: Check if CTFd directory exists and is a git repository
  ansible.builtin.stat:
    path: "{{ ctfd.path }}/.git"
  register: git_repo

- name: clone CTFd repository
  git:
    repo: "{{ ctfd.repo }}"
    dest: "{{ ctfd.path }}"
    version: "{{ ctfd.version }}"
  when: not git_repo.stat.exists


- name: increase ctfd workers
  ansible.builtin.replace:
    path: "{{ ctfd.path }}/docker-compose.yml"
    regexp: 'WORKERS=1'
    replace: 'WORKERS=4'

- name: increase nginx workers
  ansible.builtin.replace:
    path: "{{ ctfd.path }}/conf/nginx/http.conf"
    regexp: 'worker_processes\s+\d+;'
    replace: 'worker_processes 8;'
- name: increase connection limit
  ansible.builtin.replace:
    path: "{{ ctfd.path }}/conf/nginx/http.conf"
    regexp: 'worker_connections\s+\d+;'
    replace: 'worker_connections 2048;'

- name: check if ctfd secret key exists
  ansible.builtin.stat:
    path: "{{ ctfd.path }}/.ctfd_secret_key"
  register: ctfd_secret_key

- name: generate ctfd secret key
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits length=64') }}"
    dest: "{{ ctfd.path }}/.ctfd_secret_key"
  when: not ctfd_secret_key.stat.exists


- name: clone CTFd repository
  git:
    repo: "{{ ctfd_whale_repo }}"
    dest: "{{ ctfd.path }}/CTFd/plugins/ctfd-whale"
    version: "{{ ctfd_whale_branch }}"

- name: Copy needed certifactes and keys
  ansible.builtin.copy:
    src: "./docker_tls/{{ item }}"
    dest: "{{ ctfd.path }}"
    mode: "0644"
  with_items:
    - "ca.pem"
    - "cert.pem"
    - "key.pem"


- name: run docker compose
  command: docker compose up -d
  args:
    chdir: "{{ ctfd.path }}"